server:
    port: 8080
    encoding: UTF-8

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:3306/postgres
        username: nsome
        password: nsome123qwe

logging:
    level:
        org.hibernate:
            SQL: debug
            type.descriptor.sql: trace